"""added last_seen

Revision ID: 1d72ca5efe15
Revises: 26022cdc8160
Create Date: 2014-03-29 17:10:50.889064

"""

# revision identifiers, used by Alembic.
revision = '1d72ca5efe15'
down_revision = '26022cdc8160'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(),
                  nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
