"""added timestamps for user creation and update

Revision ID: 26022cdc8160
Revises: 4a76b1bbde26
Create Date: 2014-03-29 14:57:04.372086

"""

# revision identifiers, used by Alembic.
revision = '26022cdc8160'
down_revision = '4a76b1bbde26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    ### end Alembic commands ###
