"""create user favorites

Revision ID: 4748560aef80
Revises: 36674b393934
Create Date: 2014-08-21 08:09:19.490940

"""

# revision identifiers, used by Alembic.
revision = '4748560aef80'
down_revision = '36674b393934'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_series',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_series')
    ### end Alembic commands ###
